Implement code coverage job

diff --git a/.github/workflows/product-api-pipeline.yml b/.github/workflows/product-api-pipeline.yml
--- a/.github/workflows/product-api-pipeline.yml
+++ b/.github/workflows/product-api-pipeline.yml
@@ -7,9 +7,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
       - uses: actions/checkout@v3
-      - name: Set up JDK 17
 
+      - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
@@ -23,9 +24,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
       - uses: actions/checkout@v3
-      - name: Set up JDK 17
 
+      - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
@@ -34,3 +36,32 @@ jobs:
       - name: Run unit tests
         run: mvn test --batch-mode --no-transfer-progress
         working-directory: product-api/
+
+  coverage:
+    name: Code Coverage Check
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Build and Test with JaCoCo
+        run: mvn clean test jacoco:report
+
+      - name: Check Code Coverage
+        run: |
+          coverage_percentage=$(xmllint --xpath "sum(//counter[@type='INSTRUCTION']/@covered) div sum(//counter[@type='INSTRUCTION']/@missed) * 100" target/site/jacoco/jacoco.xml)
+          echo "Code coverage: $coverage_percentage%"
+          
+          if [ $(echo "$coverage_percentage >= 70" | bc -l) -eq 1 ]; then
+            echo "Code coverage is sufficient. Coverage passed!"
+          else
+            echo "Code coverage is below 70%. Coverage failed!"
+            exit 1
+          fi
